package {

	import flash.display.MovieClip;
	import fl.motion.*;
	import fl.motion.easing.*;
	import fl.containers.*;
	import fl.controls.*;
	import fl.core.*;
	import flash.net.*;
	import fl.transitions.Tween;
	import fl.transitions.Blinds;
	import fl.transitions.Fade;
	import fl.transitions.Fly;
	import fl.transitions.Iris;
	import fl.transitions.Photo;
	import fl.transitions.PixelDissolve;
	import fl.transitions.Rotate;
	import fl.transitions.Squeeze;
	import fl.transitions.Transition;
	import fl.transitions.TransitionManager;
	import fl.transitions.TweenEvent;
	import fl.transitions.Wipe;
	import fl.transitions.Zoom;
	import fl.transitions.easing.Back;
	import fl.transitions.easing.Bounce;
	import fl.transitions.easing.Elastic;
	import fl.transitions.easing.None;
	import fl.transitions.easing.Regular;
	import fl.transitions.easing.Strong;
	import fl.video.FLVPlayback;
	import fl.video.AutoLayoutEvent;
	import fl.video.ConnectClient;
	import fl.video.ControlData;
	import fl.video.CuePointManager;
	import fl.video.CuePointType;
	import fl.video.FPADManager;
	import fl.video.Icon;
	import fl.video.INCManager;
	import fl.video.IVPEvent;
	import fl.video.LayoutEvent;
	import fl.video.MetadataEvent;
	import fl.video.NCManager;
	import fl.video.ParseResults;
	import fl.video.QueuedCommand;
	import fl.video.ReconnectClient;
	import fl.video.SeekBarAccImpl;
	import fl.video.SkinErrorEvent;
	import fl.video.SMILManager;
	import fl.video.SoundEvent;
	import fl.video.UIManager;
	import fl.video.VideoAlign;
	import fl.video.VideoError;
	import fl.video.VideoEvent;
	import fl.video.VideoPlayer;
	import fl.video.VideoPlayerClient;
	import fl.video.VideoPlayerState;
	import fl.video.VideoProgressEvent;
	import fl.video.VideoScaleMode;
	import fl.video.VideoState;
	import fl.video.VolumeBarAccImpl;

	public class MainAs3Lib extends MovieClip {


		public function MainAs3Lib() {
			fl.motion.AdjustColor;
			fl.motion.Animator;
			fl.motion.Animator3D;
			fl.motion.AnimatorFactory;
			fl.motion.AnimatorFactory3D;
			fl.motion.AnimatorFactoryUniversal;
			fl.motion.AnimatorUniversal;
			fl.motion.BezierEase;
			fl.motion.BezierSegment;
			fl.motion.Color;
			fl.motion.ColorMatrix;
			fl.motion.CustomEase;
			fl.motion.DynamicMatrix;
			fl.motion.FunctionEase;
			fl.motion.ITween;
			fl.motion.Keyframe;
			fl.motion.MatrixTransformer;
			fl.motion.MatrixTransformer3D;
			fl.motion.Motion;
			fl.motion.MotionEvent;
			fl.motion.RotateDirection;
			fl.motion.SimpleEase;
			fl.motion.Source;
			fl.motion.Tweenables;
			fl.motion.easing.Back;
			fl.motion.easing.Bounce;
			fl.motion.easing.Circular;
			fl.motion.easing.Cubic;
			fl.motion.easing.Elastic;
			fl.motion.easing.Exponential;
			fl.motion.easing.Linear;
			fl.motion.easing.Quadratic;
			fl.motion.easing.Quartic;
			fl.motion.easing.Quintic;
			fl.motion.easing.Sine;
			flash.net.GroupSpecifier;
			flash.net.NetGroup;
			flash.net.NetGroupInfo;
			flash.net.NetGroupReceiveMode;
			flash.net.NetGroupReplicationStrategy;
			flash.net.NetGroupSendMode;
			flash.net.NetGroupSendResult;
			fl.transitions.Tween;
			fl.transitions.Blinds;
			fl.transitions.Fade;
			fl.transitions.Fly;
			fl.transitions.Iris;
			fl.transitions.Photo;
			fl.transitions.PixelDissolve;
			fl.transitions.Rotate;
			fl.transitions.Squeeze;
			fl.transitions.Transition;
			fl.transitions.TransitionManager;
			fl.transitions.TweenEvent;
			fl.transitions.Wipe;
			fl.transitions.Zoom;
			fl.transitions.easing.Back;
			fl.transitions.easing.Bounce;
			fl.transitions.easing.Elastic;
			fl.transitions.easing.None;
			fl.transitions.easing.Regular;
			fl.transitions.easing.Strong;
			fl.containers.ScrollPane;
			fl.video.AutoLayoutEvent;
			fl.video.ConnectClient;
			fl.video.ControlData;
			fl.video.CuePointManager;
			fl.video.CuePointType;
			fl.video.FLVPlayback;
			fl.video.FPADManager;
			fl.video.Icon;
			fl.video.INCManager;
			fl.video.IVPEvent;
			fl.video.LayoutEvent;
			fl.video.MetadataEvent;
			fl.video.NCManager;
			fl.video.ParseResults;
			fl.video.QueuedCommand;
			fl.video.ReconnectClient;
			fl.video.SeekBarAccImpl;
			fl.video.SkinErrorEvent;
			fl.video.SMILManager;
			fl.video.SoundEvent;
			fl.video.UIManager;
			fl.video.VideoAlign;
			fl.video.VideoError;
			fl.video.VideoEvent;
			fl.video.VideoPlayer;
			fl.video.VideoPlayerClient;
			fl.video.VideoPlayerState;
			fl.video.VideoProgressEvent;
			fl.video.VideoScaleMode;
			fl.video.VideoState;
			fl.video.VolumeBarAccImpl;
		}
	}

}