


<xml>
	
	<record>
		<id>1</id>
		<name>新疆</name>
		<msg></msg>
                <x>0</x>
		<y>20</y>
		<url>share/xibei/xibei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>2</id>
		<name>甘肃</name>
		<msg>白菜干 、葫芦河牌有机苹果、</msg>
                <x>15</x>
		<y>-5</y>
		<url>share/xibei/xibei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>3_1</id>
		<name>内蒙古东部</name>
		<msg>葵花、葵花籽、合作开发蔬菜大棚项目、</msg>
		<x>0</x>
		<y>0</y>
		<url>share/huabei/huabei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>3_2</id>
		<name>内蒙古中部</name>
		<msg>葵花、葵花籽、合作开发蔬菜大棚项目、</msg>
		<x>0</x>
		<y>0</y>
		<url>share/huabei/huabei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>3_3</id>
		<name>内蒙古西部</name>
		<msg>葵花、葵花籽、合作开发蔬菜大棚项目、</msg>
		<x>0</x>
		<y>0</y>
		<url>share/huabei/huabei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>4</id>
		<name>黑龙江</name>
		<msg>寻求合作伙伴、</msg>
                <x>20</x>
		<y>25</y>
		<url>share/dongbei/dongbei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>5</id>
		<name>吉林</name>
		<msg>辽杂F5109葵花籽、野猪、吉林白城70墒耕地转让、</msg>
		<url>share/dongbei/dongbei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>6</id>
		<name>辽宁</name>
		<msg>"闫店牌"甘薯。、大量供应水晶红富士苹果、大量巨峰葡萄出售、</msg>
                <x>0</x>
		<y>-6</y>
		<url>share/dongbei/dongbei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>7</id>
		<name>河北</name>
		<msg>葡萄苗果树苗、葡萄苗果树苗、饲料枣，枣粉、</msg>
                <x>-13</x>
		<y>20</y>
		<url>share/huabei/huabei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>8</id>
		<name>北京</name>
		<msg>有机杂粮、好运礼品卡，锦绣大地礼...、北京专业拆除、</msg>
		<url>share/huabei/huabei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>9</id>
		<name>天津</name>
		<msg>022-8689898...、大白菜、黄金被厂家批发 、</msg>
                <x>12</x>
		<y>8</y>
		<url>share/huabei/huabei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>10</id>
		<name>西藏</name>
		<msg></msg>
                <x>-5</x>
		<y>5</y>
		<url>share/xinan/xinan.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>11</id>
		<name>青海</name>
		<msg></msg>
		<url>share/xibei/xibei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
	<record>
		<id>12</id>
		<name>宁夏</name>
		<msg>玉米、荞麦、小米、黄米...、</msg>
		<url>share/xibei/xibei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>13</id>
		<name>陕西</name>
		<msg>水晶红富士、红富士苹果、膜袋富士、</msg>
                <x>4</x>
		<y>24</y>
		<url>share/xibei/xibei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record> 
        <record>
		<id>14</id>
		<name>山西</name>
		<msg>新鲜青三樱椒、供应毛白扬 国槐 油松、亚麻籽（胡麻籽）、</msg>
                <x>-3</x>
		<y>0</y>
		<url>share/huabei/huabei.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>15</id>
		<name>山东</name>
		<msg>肉牛、提供肉牛 如何养牛 养...、规模化养牛 消毒养牛 ...、</msg>
                <x>-8</x>
		<y>0</y>
		<url>share/huadong/huadong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>16</id>
		<name>河南</name>
		<msg>核桃、核桃、核桃、</msg>
                <x>-2</x>
		<y></y>
		<url>share/huazhong/huazhong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>17</id>
		<name>安徽</name>
		<msg>桂花树、萝卜、糙米 胚芽米、</msg>
                <x>-2</x>
		<y>0</y>
		<url>share/huadong/huadong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>18</id>
		<name>江苏</name>
		<msg>杨树苗、仔猪 母猪、苗猪 仔猪 小猪 母猪...、</msg>
                <x>5</x>
		<y>0</y>
		<url>share/huadong/huadong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>19</id>
		<name>四川</name>
		<msg>供应四川核桃苗|绵阳核...、</msg>
                <x>-2</x>
		<y>-6</y>
		<url>share/xinan/xinan.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>20</id>
		<name>重庆</name>
		<msg>大红袍柑橘、2010重庆农产品交易...、</msg>
		<url>share/xinan/xinan.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>21</id>
		<name>湖北</name>
		<msg>本公司大量收购玉米、高...、 五龙饲料购玉米，小麦...、湖北孝感营销中心是五粮...、</msg>
                <x>3</x>
		<y>0</y>
		<url>share/huazhong/huazhong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>22</id>
		<name>浙江</name>
		<msg>蜜橘、供应各种茶苗、</msg>
		<url>share/huadong/huadong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>23</id>
		<name>上海</name>
		<msg>销售海西电子吊称价格、白锈净 、杀菌剂、</msg>
                <x>15</x>
		<y>2</y>
		<url>share/huadong/huadong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>24</id>
		<name>云南</name>
		<msg>生姜、玫瑰种苗、大量供应百合种球、</msg>
        <x>0</x>
		<y>10</y>
		<url>share/xinan/xinan.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>25</id>
		<name>贵州</name>
		<msg></msg>
        <x>5</x>
		<y>0</y>
		<url>share/xinan/xinan.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>26</id>
		<name>湖南</name>
		<msg>桔子 橙子、美国山核桃种子 美国山...、黄花菜种苗、</msg>
        <x>0</x>
		<y>-7</y>
		<url>share/huazhong/huazhong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>27</id>
		<name>江西</name>
		<msg>温州柑橘、 赣南脐橙、香山果园、</msg>
                <x>-10</x>
		<y>0</y>
		<url>share/huazhong/huazhong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>28</id>
		<name>福建</name>
		<msg>福建特级川耳、供应福建干木耳、福建2009年新出香菇...、</msg>
		<url>share/huadong/huadong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>29</id>
		<name>广西</name>
		<msg>供应吊瓜子苗、沙塘桔苗、广西木瓜，荔浦马蹄、</msg>
                <x>8</x>
		<y>4</y>
		<url>share/huanan/huanan.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>30</id>
		<name>广东</name>
		<msg>常年供应广东阳江鹅苗、出售广东白沙狮头鹅苗 ...、出售广东阳江鹅苗 马冈...、</msg>
                <x>0</x>
		<y>-5</y>
		<url>share/huanan/huanan.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>31</id>
		<name>台湾</name>
		<msg></msg>
		<url>share/huazhong/huazhong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>32</id>
		<name>海南</name>
		<msg>西瓜、</msg>
		<url>share/huanan/huanan.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>33</id>
		<name>澳门</name>
		<msg></msg>
                <x>-10</x>
		<y>13</y>
		<url>share/huazhong/huazhong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>
        <record>
		<id>34</id>
		<name>香港</name>
		<msg></msg>
                <x>15</x>
		<y>8</y>
		<url>share/huazhong/huazhong.html</url>
		<target>_self</target>
		<reqtype>POST</reqtype>
	</record>

</xml>
